# Header
menu:
  主页: /
  文章: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- about_me
- category
#- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# AboutMe
about_me:
  name: '苏同'
  gender: '男'
  from: '浙江温州'
  major: '信息与计算科学'
  qq: '821192673'
  email: '821192673@qq.com'
  
